# -- The resource name suffix
nameOverride: ""
# -- The full resource name override
fullnameOverride: ""

image:
  # -- The container image to run
  repository: ghcr.io/pocket-id/pocket-id
  # -- The pull policy for images
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart version.
  distroless: false
  tag: ""

# -- Choose backend for large binary objects (e.g. logo, background images, ...)
# Valid values are: "filesystem", "database" or "s3".
# Set's Pocket ID `FILE_BACKEND` property
blobBackend: "database"

# -- Set Url for Pocket ID instance
# Set's Pocket ID `APP_URL` property with prepended https:// and adds hostname to HttpRoute
appUrl: "auth.example.com"

# -- Pocket-id configuration variables
# For more information and full list of options see: https://pocket-id.org/docs/configuration/environment-variables
config: {}
  # trustProxy: ""
  # maxmindLicenseKey: ""
  # dbConnectionString: ""
  # uploadPath: ""
  # geoliteDbPath: ""
  # logLevel: info  
  # # maxmindLicenseKey: (use secret)
  # # encryptionKey: (use secret)
  # geoliteDbPath: 
  # uiConfigDisabled: 
  # appName: 
  # emailsVerified: 
  # smtpHost: mail.example.com
  # smtpPort: "465"
  # smtpFrom: pocketid@example.com
  # # smtpUser:  (use secret)
  # # smtpPassword:  (use secret)
  # smtpTls:
  # smtpSkpCertVerify:
  # allowUserSignups: 
  # emailLoginNotificationEnabled:
  # emailOneTimeAccessAsAdminEnabled:
  # emailApiKeyExpirationEnabled:
  # emailOneTimeAccessAsUnauthenticatedEnabled:
  # accentColor: "oklch(0.6 0.27 357.52)"
  # logJson:
  # logLevel: 
  # disableRateLimiting:
  # homePageUrl: /settings/apps

# Name of an existing config map containing any environment variables. 
# All automatically added settings need to be added.
# @ignored
existingConfigMap: ""

# -- Name of an existing secret containing any environment variables
# Add secret containing **ENCRYPTION_KEY** and if applicable SMTP_USER, SMTP_PASSWORD, ...
existingSecret: ""

# -- Secret for a database connection string 
# Supply name of secret and key containing a fully qualified uri for the database connection.
# *Using config to supply the database connection string is not recommended*
connectionString: {}
  # -- Name of secret
  # name: pocketid-cluster-app
  # -- Key containing a fully qualified uri for the database connection
  # key: fqdn-uri

# -- This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

# -- Security context. 
# If supplied runAsUser is used for Pocket ID `PUID`.
# If supplied runAsGroup is used for Pocket ID `PGID`
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 1000  

# @ignored
service:
  type: ClusterIP
  port: 1411

ingress:
  # -- Enables an ingress for the application  (use either ingress or httpRoute)
  enabled: false
  className: ""
  # -- Annotations for the ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  # -- Adds tls to the ingress
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
# @default -- {}
httpRoute:
  # -- Enables a Gateway API HTTPRoute (use either ingress or httpRoute)
  enabled: false
  # -- HTTPRoute annotations.
  annotations: {}
  # -- Which Gateways this Route is attached to.
  # @default -- {}  
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # -- Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # -- List of rules and filters applied.
  # @default -- {}  
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

# -- Specifiy resources for the pod
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  initialDelaySeconds: 60
  httpGet:
    # -- Healthcheck endpoint
    path: /health
    port: http
readinessProbe:
  initialDelaySeconds: 15
  httpGet:
    # -- Healthcheck endpoint
    path: /health
    port: http

persistence:
  # -- Persist data to a persistent volume
  enabled: true
  # -- A manually managed Persistent Volume and Claim
  # Requires persistence.enabled: true
  # If defined, PVC must be created manually before volume will be bound
  existingClaim: ""
  # -- Persistent Volume Storage Class
  # If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined (the default) or set to null, no storageClassName spec is
  #   set, choosing the default provisioner.  (gp2 on AWS, standard on
  #   GKE, AWS & OpenStack)
  storageClass: ""
  annotations: {}
  accessMode: ReadWriteOnce
  size: 8Gi

# -- Additional volumes on the pod definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the pod definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
